//
//  ConfirmationCodeProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 8.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol ConfirmationCodeViewControllerProtocol: BaseViewControllerProtocol {
    
    func showVerification()
    func showAddressSelection()
    func keyboardWillChange(notification: NSNotification)
    func complateAddressSelection(address: AddressModel)
    func goToHomeScreen()
}

// MARK: - Presenter

protocol ConfirmationCodePresenterViewProtocol: BasePresenterViewProtocol {
    
    var bodyLabelText: String { get }
    var state: ConfirmationViewState! { get set }
    
    func sendVerificationCode()
    func confirmCode(confirmationCode: String)
    func updateAddressInformation(address: AddressModel)
    func setConfirmationVeriables()
}

protocol ConfirmationCodePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func presentVerification()
    func presentAddressSelection()
    func presentHomeScreen()
}

protocol ConfirmationCodePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol ConfirmationCodeInteractorProtocol: BaseInteractorProtocol {
    
    func sendSMS(phoneNumber: String, countryCode: String)
    func callConfirmation(confirmationCode: String, phoneNumber: String)
    func updateAddressInformation(address: AddressModel)
}
