//
//  SplashProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 1.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol SplashViewControllerProtocol: BaseViewControllerProtocol {
    
}

// MARK: - Presenter

protocol SplashPresenterViewProtocol: BasePresenterViewProtocol {
    
}

protocol SplashPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
}

protocol SplashPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol SplashInteractorProtocol: BaseInteractorProtocol {
    
}
