//
//  FollowViewController.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class FollowViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var profilePicture: UIImageView!
    @IBOutlet weak var username: UILabel!
    @IBOutlet weak var addressDesc: UILabel!
    
    // MARK: - Dependencies
    
    var presenter: FollowPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        tabBarController?.selectedIndex = 4
        
        if let user = MessagingAppGlobal.shared.userModel {
            if let pictureURL = user.profilePicture {
                profilePicture.setImage(url: pictureURL)
            }
            profilePicture.makeRounded()
        }
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        barTitle = "letter_time_tracking".localized
        setRightNavigationBarItem(image: #imageLiteral(resourceName: "settingsButton.png"), action: #selector(showProfile))
        
        if let user = MessagingAppGlobal.shared.userModel {
            username.text = user.firstName + " " + user.lastName
            addressDesc.text = user.address.description
            if let pictureURL = user.profilePicture {
                profilePicture.setImage(url: pictureURL)
            }
            profilePicture.makeRounded()
        }
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
    @IBAction func expectedLetterButtonTapped(_ sender: Any) {
        if let navigationController = navigationController {
            FollowIncomingWireframe().show(transitionType: .push(navigationController: navigationController, animated: true))
        }
    }
    
    @IBAction func toBeTransmittedLetterButtonTapped(_ sender: Any) {
        if let navigationController = navigationController {
            FollowOutgoingWireframe().show(transitionType: .push(navigationController: navigationController, animated: true))
        }
    }
}

// MARK: - Extensions

// MARK: - Protocol Implemantations

extension FollowViewController: FollowViewControllerProtocol {
    
}
