//
//  FollowProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol FollowViewControllerProtocol: BaseViewControllerProtocol {
    
}

// MARK: - Presenter

protocol FollowPresenterViewProtocol: BasePresenterViewProtocol {
    
}

protocol FollowPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
}

protocol FollowPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol FollowInteractorProtocol: BaseInteractorProtocol {
    
}
