//
//  OnboardingProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 1.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol OnboardingViewControllerProtocol: BaseViewControllerProtocol {
    
}

// MARK: - Presenter

protocol OnboardingPresenterViewProtocol: BasePresenterViewProtocol {
    
}

protocol OnboardingPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
}

protocol OnboardingPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol OnboardingInteractorProtocol: BaseInteractorProtocol {
    
}
