//
//  OnboardingViewController.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 1.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class OnboardingViewController: BaseViewController {
    
    // MARK: - Outlets
    
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var pageControl: UIPageControl!
    @IBOutlet weak var skipButton: UIButton!
    @IBOutlet weak var nextButton: UIButton!
    
    // MARK: - Dependencies
    
    var presenter: OnboardingPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        pageControl.numberOfPages = 3
        pageControl.currentPage = 0
        
        collectionView.isPagingEnabled = true
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
        pageControl.currentPage = Int(scrollView.contentOffset.x + scrollView.frame.width/2) / Int(scrollView.frame.width)
        
        
        switch pageControl.currentPage {
        case 2:
            nextButton.setTitle("finish".localized, for: .normal)
            skipButton.isEnabled = false
            skipButton.setTitle("completed".localized, for: .disabled)
        default:
            nextButton.setTitle( "next".localized, for: .normal)
            skipButton.isEnabled = true
            skipButton.setTitle("skip".localized, for: .normal)
        }
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
    @IBAction func skipButtonTapped(_ sender: Any) {
        
        let userDefaults = UserDefaults.standard
        userDefaults.set(true, forKey: "hasRunBefore")
        userDefaults.synchronize()
        LoginWireframe().show(transitionType: .root)
    }
    
    @IBAction func nextButtonTapped(_ sender: Any) {
        
        if pageControl.currentPage == 2 {
            self.skipButtonTapped(self)
            return
        }
        
        let collectionBounds = self.collectionView.bounds
        let contentOffset = CGFloat(floor(self.collectionView.contentOffset.x + collectionBounds.size.width))
        self.moveCollectionToFrame(contentOffset: contentOffset)
        
    }

    func moveCollectionToFrame(contentOffset : CGFloat) {
        
        let frame: CGRect = CGRect(x : contentOffset ,y : self.collectionView.contentOffset.y ,width : self.collectionView.frame.width,height : self.collectionView.frame.height)
        self.collectionView.scrollRectToVisible(frame, animated: true)
    }
}

// MARK: - Extensions

extension OnboardingViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 3
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        switch indexPath.item {
        case 0:
            return collectionView.dequeueReusableCell(withReuseIdentifier: "cell0", for: indexPath)
        case 1:
            return collectionView.dequeueReusableCell(withReuseIdentifier: "cell1", for: indexPath)
        case 2:
            return collectionView.dequeueReusableCell(withReuseIdentifier: "cell2", for: indexPath)
        default:
            return UICollectionViewCell()
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {

        return CGSize(width: view.frame.width, height: view.frame.height)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
}

// MARK: - Protocol Implemantations

extension OnboardingViewController: OnboardingViewControllerProtocol {
    
}
