//
//  HomeInteractor.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import Foundation

class HomeInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    
    var presenter: HomePresenterInteractorProtocol!
    
    // MARK: - Initialization
    
    override init(networkService: NetworkService? = nil, coreDataService: CoreDataService? = nil) {
        super.init(networkService: networkService, coreDataService: coreDataService)
    }
    
    // MARK: - Business Logic

}

// MARK: - Extensions

// MARK: - Protocols Implemantations

extension HomeInteractor: HomeInteractorProtocol {
    func callWillComingLetters() {
        
        networkService.getJSON(url: NetworkConstants.willComeLetter, success: { (json) in
            guard let statusCode = json["statusCode"].int else {
                self.presenter.handleAndShowError(errorModel: ErrorModel.default)
                return
            }
            
            switch statusCode {
            case 0:
                let willComeLettersModel = WillComeLetersModel(json: json["data"])
                self.presenter.presentLetters(letters: willComeLettersModel.letters)
                break
            default:
                self.presenter.handleAndShowError(errorModel: Errors.somethingsWrong)
            }
        }) { (errorModel) in
            self.presenter.handleAndShowError(errorModel: errorModel)
        }
    }
}
