//
//  HomeProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol HomeViewControllerProtocol: BaseViewControllerProtocol {
    
    func showWillComingLetters(letters: [LetterModel])
}

// MARK: - Presenter

protocol HomePresenterViewProtocol: BasePresenterViewProtocol {
    
    func getWillComingLetters()
}

protocol HomePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func presentLetters(letters: [LetterModel])
}

protocol HomePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol HomeInteractorProtocol: BaseInteractorProtocol {
    
    func callWillComingLetters()
}
