//
//  FollowIncomingProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 4.05.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol FollowIncomingViewControllerProtocol: BaseViewControllerProtocol {
    func showLetters(_ letters: [LetterModel])
}

// MARK: - Presenter

protocol FollowIncomingPresenterViewProtocol: BasePresenterViewProtocol {
    func fetchLetters()
}

protocol FollowIncomingPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func presentLetters(_ letters: [LetterModel])
}

protocol FollowIncomingPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol FollowIncomingInteractorProtocol: BaseInteractorProtocol {
    func fetchLetters()
}
