//
//  OutgoingWireframe.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

class OutgoingWireframe: BaseWireframe {
    
    func initializeTabBar(tabBarController: UITabBarController, tabBarItem: UITabBarItem, delegate: OutgoingPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        let viewController: OutgoingViewController = UIStoryboard.tabBar.instantiateViewController()
        let navigationController = UINavigationController(rootViewController: viewController)
        
        let interactor = OutgoingInteractor(networkService: NetworkService.sharedInstance)
        
        let presenter = OutgoingPresenter(viewController: viewController, interactor: interactor, delegate: nil, extras: nil)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        navigationController.tabBarItem = tabBarItem
        tabBarController.addChild(navigationController)
    }
}
