//
//  OutgoingPresenter.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import Foundation

class OutgoingPresenter: BasePresenter {
    
    // MARK: - Dependencies
    
    fileprivate var viewController: OutgoingViewControllerProtocol!
    fileprivate var interactor: OutgoingInteractorProtocol!
    fileprivate var delegate: OutgoingPresenterDelegateProtocol?
    
    // MARK: - Extras
    
    // MARK: - Properties
    
    // MARK: - Initialization
    
    init(viewController: OutgoingViewControllerProtocol, interactor: OutgoingInteractorProtocol, delegate: OutgoingPresenterDelegateProtocol?, extras: Any?) {
        self.viewController = viewController
        self.interactor = interactor
        self.delegate = delegate
        
        // Store extras
    }
    
    // MARK: - Business Logic
    
    // MARK: - Override
    
    override func handleAndShowError(errorModel: ErrorModel) {
        
        viewController.stopProgress()
        if handleError(errorModel: errorModel, viewController: viewController) {
            viewController.showError(errorModel: errorModel)
        }
    }
}

// MARK: - Extensions

// MARK: - Protocols Implemantations

// MARK: View Protocol

extension OutgoingPresenter: OutgoingPresenterViewProtocol {
    
    func fetchLetters() {
        viewController.startLoading()
        interactor.fetchLetters()
    }
}

// MARK: Interactor Protocol

extension OutgoingPresenter: OutgoingPresenterInteractorProtocol {
    
    func presentLetters(_ letters: [LetterModel], _ incomingCount: Int, _ outgoingCount: Int) {
        viewController.stopLoading()
        viewController.showLetters(letters, incomingCount, outgoingCount)
    }
}

// MARK: Delegate Protocol

