//
//  OutgoingProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 11.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol OutgoingViewControllerProtocol: BaseViewControllerProtocol {
    func showLetters(_ letters: [LetterModel], _ incomingCount: Int, _ outgoingCount: Int)
}

// MARK: - Presenter

protocol OutgoingPresenterViewProtocol: BasePresenterViewProtocol {
    func fetchLetters()
}

protocol OutgoingPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func presentLetters(_ letters: [LetterModel], _ incomingCount: Int, _ outgoingCount: Int)
}

protocol OutgoingPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol OutgoingInteractorProtocol: BaseInteractorProtocol {
    func fetchLetters()
}
