//
//  PreviewViewController.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 10.05.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class PreviewViewController: BaseViewController {
    
    // MARK: - Outlets
    
    @IBOutlet weak var stampImage: UIImageView!
    @IBOutlet weak var envelopeImage: UIImageView!
    
    // MARK: - Dependencies
    
    var presenter: SendLetterPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        if let stampType = presenter.stampType?.value,
            let envelopeType = presenter.envelopeType?.value {
            stampImage.image = UIImage(named: "stamp\(stampType)")
            envelopeImage.image = UIImage(named: "envelope\(envelopeType)")
        }
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        barTitle = "preview".localized
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
    @IBAction func nextButtonTapped(_ sender: Any) {
        let nextController: SelectPaperViewController = UIStoryboard.sendLetter.instantiateViewController()
        presenter.selectPaperViewController = nextController
        nextController.presenter = presenter
        
        navigationController?.pushViewController(nextController, animated: false)
    }
    
    @IBAction func backButtonTapped(_ sender: Any) {
        self.leftTapped()
    }
}

// MARK: - Extensions

// MARK: - Protocol Implemantations
