//
//  SelectPaperViewController.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 15.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit
import AnimatedCollectionViewLayout

class SelectPaperViewController: BaseViewController {
    
    // MARK: - Outlets
    
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var pageControl: UIPageControl!
    
    // MARK: - Dependencies
    
    var presenter: SendLetterPresenterViewProtocol!
    
    // MARK: - Properties
    
    var selectedPaper = PaperType.paperType1
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        barTitle = "choose_your_paper".localized
        
        let layout = AnimatedCollectionViewLayout()
        layout.animator = LinearCardAttributesAnimator()
        layout.scrollDirection = .horizontal
        layout.itemSize = CGSize(width: collectionView.frame.width, height: collectionView.frame.height)
        
        collectionView.collectionViewLayout = layout
        collectionView.delegate = self
        collectionView.dataSource = self
        collectionView.isPagingEnabled = true
        
        pageControl.numberOfPages = 10
        pageControl.currentPage = 0
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        pageControl.currentPage = Int(scrollView.contentOffset.x + scrollView.frame.width/2) / Int(scrollView.frame.width)
        selectedPaper = PaperType(rawValue: pageControl.currentPage + 1) ?? selectedPaper
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
    @IBAction func backButtonTapped(_ sender: Any) {
        self.leftTapped()
    }
    
    @IBAction func nextButtonTapped(_ sender: Any) {
        
        presenter.paperType = selectedPaper
        
        let nextController: WriteViewController = UIStoryboard.sendLetter.instantiateViewController()
        presenter.writeViewController = nextController
        nextController.presenter = presenter
        
        navigationController?.pushViewController(nextController, animated: false)
    }
    
}

// MARK: - Extensions

extension SelectPaperViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 10
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "paperCell", for: indexPath) as! PaperCell
        cell.imageView.image = UIImage(named: "paper\(indexPath.row + 1)")
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: collectionView.frame.width, height: collectionView.frame.height * 1.4)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        return .zero
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
}

// MARK: - Protocol Implemantations

extension SelectPaperViewController: SelectPaperViewControllerProtocol {
    
}
