# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messaging App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messaging App
  pod 'Alamofire', '~> 4.0'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'AnimatedCollectionViewLayout'
  pod 'PhoneNumberKit', '~> 3.3'
end
