//
//  ForgetPasswordProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 8.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol ForgetPasswordViewControllerProtocol: BaseViewControllerProtocol {
    func showSuccess()
}

// MARK: - Presenter

protocol ForgetPasswordPresenterViewProtocol: BasePresenterViewProtocol {
    func sendRequest(email: String)
}

protocol ForgetPasswordPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func presentSuccess()
}

protocol ForgetPasswordPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol ForgetPasswordInteractorProtocol: BaseInteractorProtocol {
    func sendRequest(email: String)
}
