//
//  ForgetPasswordViewController.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 8.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class ForgetPasswordViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var emailText: CustomTextField!
    
    // MARK: - Dependencies
    
    var presenter: ForgetPasswordPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    @IBAction func nextButtonTapped(_ sender: Any) {
        if let email = emailText.text {
            presenter.sendRequest(email: email)
        }
    }
    
    @IBAction func closeButtonTapped(_ sender: Any) {
        LoginWireframe().show(transitionType: .root)
    }
    
}

// MARK: - Extensions

extension ForgetPasswordViewController: UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
}

// MARK: - Protocol Implemantations

extension ForgetPasswordViewController: ForgetPasswordViewControllerProtocol {
    
    func showSuccess() {
        showPopup(title: "success".localized, message: "message_text.successfully_sent_password_reset_link".localized) { (_) in
            LoginWireframe().show(transitionType: .root)
        }
    }
}
