//
//  BaseInteractor.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 1.03.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import Foundation

class BaseInteractor {
    
    // MARK: - Properties
    
    internal var coreDataService: CoreDataService!
    internal var networkService: NetworkService!

    init(networkService: NetworkService?, coreDataService: CoreDataService?) {
        if let networkService = networkService {
            self.networkService = networkService
        }
        if let coreDataService = coreDataService {
            self.coreDataService = coreDataService
        }
    }
    
}

// MARK: - Extensions

// MARK: - Protocols Implemantations

extension BaseInteractor: BaseInteractorProtocol {
    
}
