//
//  SettingsWireframe.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 15.04.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

class SettingsWireframe: BaseWireframe {
    
    // TODO: Use tuples for extras if you have more than once parameters
    func show(transitionType: WireframeTransitionType, delegate: SettingsPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        // TODO: Choose related storyboard
        let viewController: SettingsViewController = UIStoryboard.main.instantiateViewController()
        
        // TODO: Inteactor Dependencies
        let interactor = SettingsInteractor(networkService: NetworkService.sharedInstance)
        
        let presenter = SettingsPresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
