//
//  FollowOutgoingProtocols.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 4.05.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol FollowOutgoingViewControllerProtocol: BaseViewControllerProtocol {
    func showLetters(_ letters: [LetterModel])
}

// MARK: - Presenter

protocol FollowOutgoingPresenterViewProtocol: BasePresenterViewProtocol {
    func fetchLetters()
    func revertLetter(_ letterID: Int)
}

protocol FollowOutgoingPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func presentLetters(_ letters: [LetterModel])
    func refreshLetters()
}

protocol FollowOutgoingPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol FollowOutgoingInteractorProtocol: BaseInteractorProtocol {
    func fetchLetters()
    func revertLetter(_ letterID: Int)
}
