//
//  FollowOutgoingWireframe.swift
//  Messaging App
//
//  Created by Burak Çokyıldırım on 4.05.2020.
//  Copyright (c) 2020 Softbea. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

class FollowOutgoingWireframe: BaseWireframe {
    
    // TODO: Use tuples for extras if you have more than once parameters
    func show(transitionType: WireframeTransitionType, delegate: FollowOutgoingPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        // TODO: Choose related storyboard
        let viewController: FollowOutgoingViewController = UIStoryboard.Follow.instantiateViewController()
        
        // TODO: Inteactor Dependencies
        let interactor = FollowOutgoingInteractor(networkService: NetworkService.sharedInstance)
        
        let presenter = FollowOutgoingPresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
